### ISSUE TITLE
Does it still work?

### ISSUE THREAD

**Issue by butavpaul** [GloryOfNight/UE4_FirebaseAnalytics#3]
Hello. I'm interested in using your plugin for a mobile android game but when I'm compiling I get some errors. I'm using 4.25 ( First I rebuilt it manually from Visual Studio)

`UATHelper: Packaging (Android (ETC2)):   WARNING: Library 'firebase_app' was not resolvable to a file when used in Module 'FirebaseAnalytics', assuming it is a filename and will search library paths for it. This is slow and dependency checking will not work for it. Please update reference to be fully qualified alternatively use PublicSystemLibraryPaths if yo
u do intended to use this slow path to suppress this warning.
UATHelper: Packaging (Android (ETC2)):   WARNING: Library 'firebase_analytics' was not resolvable to a file when used in Module 'FirebaseAnalytics', assuming it is a filename and will search library paths for it. This is slow and dependency checking will not work for it. Please update reference to be fully qualified alternatively use PublicSystemLibraryPaths
 if you do intended to use this slow path to suppress this warning.
PackagingResults: Warning: Library 'firebase_app' was not resolvable to a file when used in Module 'FirebaseAnalytics', assuming it is a filename and will search library paths for it. This is slow and dependency checking will not work for it. Please update reference to be fully qualified alternatively use PublicSystemLibraryPaths if you do intended to use th
is slow path to suppress this warning.
PackagingResults: Warning: Library 'firebase_analytics' was not resolvable to a file when used in Module 'FirebaseAnalytics', assuming it is a filename and will search library paths for it. This is slow and dependency checking will not work for it. Please update reference to be fully qualified alternatively use PublicSystemLibraryPaths if you do intended to 
use this slow path to suppress this warning.`

>`Plugins/Firebase/Source/FirebaseAnalytics/Private/FirebaseAnalyticsBPLib.cpp(110,71): error: 'sizeof (kParameters)' will return the size of the pointer, not the array itself [-Werror,-Wsizeof-pointer-div]
UATHelper: Packaging (Android (ETC2)):                     LogEvent(TCHAR_TO_UTF8(*Category), kParameters, sizeof(kParameters) / sizeof(kParameters[0]));
UATHelper: Packaging (Android (ETC2)):                                                                     ~~~~~~~~~~~~~~~~~~~ ^
UATHelper: Packaging (Android (ETC2)):     1 error generated.
UATHelper: Packaging (Android (ETC2)):     [10/19] TheRoad.cpp [armv7]
UATHelper: Packaging (Android (ETC2)):     [11/19] Empty.cpp [armv7]
PackagingResults: Error: 'sizeof (kParameters)' will return the size of the pointer, not the array itself [-Werror,-Wsizeof-pointer-div]
UATHelper: Packaging (Android (ETC2)):     [12/19] TheRoad.cpp [arm64]
UATHelper: Packaging (Android (ETC2)):     [13/19] Empty.cpp [arm64]
UATHelper: Packaging (Android (ETC2)):     [14/19] Module.FirebaseAnalytics.cpp [arm64]
UATHelper: Packaging (Android (ETC2)):     In file included from /Plugins/Firebase/Intermediate/Build/Android/UE4/Shipping/FirebaseAnalytics/Module.FirebaseAnalytics.cpp:3:
UATHelper: Packaging (Android (ETC2)):     /Plugins/Firebase/Source/FirebaseAnalytics/Private/FirebaseAnalyticsBPLib.cpp(110,71): error: 'sizeof (kParameters)' will return the size of the pointer, not the array itself [-Werror,-Wsizeof-pointer-div]
UATHelper: Packaging (Android (ETC2)):                     LogEvent(TCHAR_TO_UTF8(*Category), kParameters, sizeof(kParameters) / sizeof(kParameters[0]));
UATHelper: Packaging (Android (ETC2)):                                                                     ~~~~~~~~~~~~~~~~~~~ ^
UATHelper: Packaging (Android (ETC2)):     1 error generated.
PackagingResults: Error: 'sizeof (kParameters)' will return the size of the pointer, not the array itself [-Werror,-Wsizeof-pointer-div]
UATHelper: Packaging (Android (ETC2)):     [15/19] Module.FirebaseAnalytics.gen.cpp [armv7]
UATHelper: Packaging (Android (ETC2)):     [16/19] Module.FirebaseAnalytics.gen.cpp [arm64]
UATHelper: Packaging (Android (ETC2)): Took 37.7114315s to run UnrealBuildTool.exe, ExitCode=6
UATHelper: Packaging (Android (ETC2)): UnrealBuildTool failed. See log for more details. (C:\Users\Paul\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_4.25\UBT-TheRoad-Android-Shipping_2.txt)
UATHelper: Packaging (Android (ETC2)): AutomationTool exiting with ExitCode=6 (6)
UATHelper: Packaging (Android (ETC2)): BUILD FAILED
PackagingResults: Error: Unknown Error`

Can  I solve this somehow?
Thank you

**Comment by GloryOfNight** [comment]
I will check on it soon. 
Plugin need some update and fixes.

**Comment by GloryOfNight** [comment]
@butavpaul, should be fixed. Please check.
I wasn't able to fix some warnings, didn't figure out how yet. But critical errors should be gone.

**Comment by GloryOfNight** [comment]
Okay. I fixed build warnings.
Everything now should be fine.
