### ISSUE TITLE
Firebase auth, firestore features

### ISSUE THREAD

**Issue by tirumala007** [GloryOfNight/UE4_FirebaseAnalytics#4]
Can you add auth, firestore, storage to this plugin, for unreal engine ?

**Comment by GloryOfNight** [comment]
Maybe someday, but no plans for this soon.

This plugin originally was created for my work project,  we was using it like a week and then we replaced firebase with other analytics systems. So I published plugin for public use.

I probably will keep it working with new UE versions, but I don't have much time on feature development. I rly hope that community can take over the plugin and improve it over time. Really want to see some Pull Requests in future. 

Also its funny that plugin was in GitHub like a year+, and now its starting to popup to people =)
